//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlowBill
    {
        public int id { get; set; }
        public Nullable<int> phoneListId { get; set; }
        public string allPay { get; set; }
        public string time { get; set; }
        public string allFlow { get; set; }
        public string allTime { get; set; }
    }
}
