//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication.Models.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LoanEntities : DbContext
    {
        public LoanEntities()
            : base("name=LoanEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BillData> BillData { get; set; }
        public DbSet<FlowBill> FlowBill { get; set; }
        public DbSet<FlowDetail> FlowDetail { get; set; }
        public DbSet<MessageData> MessageData { get; set; }
        public DbSet<PhoneList> PhoneList { get; set; }
        public DbSet<TelData> TelData { get; set; }
    }
}
