//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhoneList
    {
        public int id { get; set; }
        public string phone { get; set; }
        public string idCard { get; set; }
        public string source { get; set; }
        public string email { get; set; }
        public string registerDate { get; set; }
        public string addr { get; set; }
        public string realName { get; set; }
        public string phoneRemain { get; set; }
    }
}
