//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TelData
    {
        public int id { get; set; }
        public Nullable<int> phoneListId { get; set; }
        public string tradeTime { get; set; }
        public string cTime { get; set; }
        public string receiverPhone { get; set; }
        public string callType { get; set; }
        public string tradeAddr { get; set; }
        public string tradeType { get; set; }
    }
}
